### ISSUE TITLE
navbar use question

### ISSUE THREAD

**Issue by mloubout** [schochastics/academicons#10]
Can those be used in the navbar of a quarto website as either a `icon` or in the `right/left` part as an icon/url pair? It doesn't seem to render the icon when I try it.

**Comment by schochastics** [comment]
I think this is not possible since the icon field only supports bootstrap icons: https://quarto.org/docs/reference/projects/websites.html#nav-items

**Comment by mloubout** [comment]
Ok thank you, yeah was trying to see if there was a way around the default bootstrap list. 

Thanks

**Comment by schochastics** [comment]
@mloubout this is untested, but might work or give you a starting point:
```yaml
 navbar:
    right:
      - href: https://arxiv.org
        text: '<i class="ai ai-1x ai-arxiv"></i>'
```
I vaguely recall that I did this or something similar in a project before
