### ISSUE TITLE
Icons are not displayed in the same color as Quarto's default ones

### ISSUE THREAD

**Issue by netw0rkf10w** [schochastics/academicons#11]
Hello,

I was suggested to report an issue with your extension. Please see the discussion here: https://github.com/quarto-dev/quarto-cli/discussions/5816

Best regards.

**Comment by schochastics** [comment]
Thanks for this, I removed black as a default color and now it should work. The sizing I am not sure how to achieve automatically. @mcanouil how did you do that with iconify (if that is possible)?
```yaml
project:
  type: website

website:
  title: "blog-quarto"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      - text: "{{< ai google-scholar size=xl >}}"
        href: https://scholar.google.fr/citations?user=xxx
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
```
