### ISSUE TITLE
How to add the icon inside the title section?

### ISSUE THREAD

**Issue by vbhavsar16** [schochastics/academicons#14]
Hello,
Thanks for this great package.

I am having trouble including the icon in the title section.

```
---
title: "About"
image: profile.jpg
about:
  template: jolla
  links:
    - icon: linkedin
      text: LinkedIn
      href: https://linkedin.com
    - icon: github
      text: Github
      href: https://github.com
    - icon: {{< ai google-scholar >}}
      text: Publications
      href: https://linkedin.com
---

About this blog
{{< ai google-scholar >}}

```

The Google Scholar icon will be executed for the last line but not for the links in the title section.

**Comment by schochastics** [comment]
Can you try this:
https://github.com/schochastics/quarto-schochastics/blob/main/_quarto.yml#L42

If I recall correctly then shortcodes do not work (at least did not) work and this should be a workaround

**Comment by vbhavsar16** [comment]
Thank you for your quick reply.

Yes, that works! I tried to change the size between 1x and 2x by using the latex parameter large/Large but that did not work. That is okay for now.

In the solution you directed me to, the icon is for the part of the footer. Similarly, it worked for the links but not for the nav bar. I saw the previous issue related to this but that solution did not work for me for the nav bar.

**Comment by schochastics** [comment]
Thanks for trying. I will investigate a bit

**Comment by vbhavsar16** [comment]
Sure, no problem!

**Comment by schochastics** [comment]
```
---
title: "About"
about:
  template: jolla
  links:
    - icon: linkedin
      text: LinkedIn
      href: https://linkedin.com
    - icon: github
      text: Github
      href: https://github.com
    - text: <i class="ai ai-google-scholar" role="img"></i> Publications
      href: https://linkedin.com
---

About this blog
{{< ai google-scholar >}}
```

does this do what you want?

**Comment by vbhavsar16** [comment]
This solution `<i class="ai ai-google-scholar" role="img"></i>` works for the links or footer.

However, it does not work for the nav bar in the _quarto.yml file.

**Comment by schochastics** [comment]
Ah sorry my bad misunderstood your comment. Will have a look st the navbar separately

**Comment by schochastics** [comment]
hopefully I finally understood your issue. As shown here: https://github.com/quarto-ext/fontawesome/issues/6, the shortcodes should work in the navbar. So the below `_quarto.yml` shows the correct icons for me in the navbar

```
project:
  type: website

website:
  title: "Test {{< ai google-scholar >}}"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: https://linkedin.com
        text: "{{< ai google-scholar >}}"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
```
