### ISSUE TITLE
how can these be used in a quarto about page?

### ISSUE THREAD

**Issue by JohnFranchak** [schochastics/academicons#2]
https://quarto.org/docs/websites/website-about.html

The example they give is via the YAML header. How could the google scholar one be put in as the icon? The short codes don't work in this placement.
```
---
title: "Finley Malloc"
about:
  template: jolla
  image: profile.jpg
  links:
    - icon: twitter
      text: twitter
      href: https://twitter.com
    - icon: github
      text: Github
      href: https://github.com
---
```
