### ISSUE TITLE
[question] How do I add an academicon in About link?

### ISSUE THREAD

**Issue by fredguth** [schochastics/academicons#6]
`About pages` may use some icons (twitter, github, etc):
https://quarto.org/docs/websites/website-about.html

Is it possible to use academicons?  how? 

I was expecting something like this:

```
---
title: Finley
about:
  template: trestles
  links:
    - text: Google Scholar
      icon: google-scholar
      url: https://
---
```
